stages:
  - validate
  - generate-clients
  - deploy

# specify the location of the Open API Specification files within your project
# and the filename of the specification that you would like to display by default
variables:
  # DOCS_FOLDER: "."
  SPEC_TO_DISPLAY: "comicvine-api.yml"

api-specification:
  image: node:10-alpine
  stage: validate
  cache:
    paths:
      - ./node_modules
  before_script:
    - npm install @apidevtools/swagger-cli
  script:
    - npx swagger-cli validate ./openapi.yml -d
    # bundle spec into one file
    - npx swagger-cli bundle -o ${SPEC_TO_DISPLAY} ./openapi.yml --type yaml
    - mkdir -p public
    - cp ${SPEC_TO_DISPLAY} public/
  artifacts:
    paths:
      - public

python:
  image:
    name: openapitools/openapi-generator:cli-latest
    entrypoint: [""]
  stage: generate-clients
  cache: {}
  before_script:
    - apk add git
    - git config --global user.name "Gitlab CI"
    - git config --global user.email "<>"
  script:
    - docker-entrypoint.sh validate  -i ./openapi.yml
    - docker-entrypoint.sh generate  -i ./openapi.yml -o client -g ${CI_JOB_NAME} --git-user-id "${GIT_USER_ID}" --git-repo-id "comicvine-client-${CI_JOB_NAME}" --release-note "${CI_COMMIT_MESSAGE}" --additional-properties=packageName=comicvine_client --http-user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
    - cp build/git_push_force.sh client/
    - cd client
    - chmod +x ./git_push_force.sh
    - ./git_push_force.sh ${GIT_USER_ID} comicvine-client-${CI_JOB_NAME} "${CI_COMMIT_MESSAGE}"

pages:
  image: node:10-alpine
  stage: deploy
  cache:
    paths:
      - ./node_modules
  before_script:
    - npm install swagger-ui-dist@3.22.1
  script:
    # create static HTML
    - mkdir -p public
    - cp -rp node_modules/swagger-ui-dist/* public
    # - cp -rp $DOCS_FOLDER/* public
    - sed -i "s#https://petstore\.swagger\.io/v2/swagger\.json#$SPEC_TO_DISPLAY#g" public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
